### ISSUE TITLE
need help trying to clone the fork 

### ISSUE THREAD

**Issue by courtneypersons** [learn-co-curriculum/git-github-learn-quiz#15]
every time i past the ssh link in the terminal i get 

Courtneys-MBP:Users courtneypersons$ git clone git@github.com:courtneypersons/first-lab-online-web-prework.git
fatal: could not create work tree dir 'first-lab-online-web-prework': Permission denied

i dont know i did wrong

**Comment by drakeltheryuujin** [comment]
Hi @courtneypersons,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum. This sounds like an environment issue. Have you tried the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out? For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/). Otherwise, we unfortunately do not have the capacity to support this type of issue at this time. I would recommend googling around about the problem.

If, after consulting the Help Center, AAQ, and googling around you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
